language:
- node_js

node_js: "11.2.0"

dist: trusty
sudo: required

branches:
  only:
  - master

cache:
  directories:
  - node_modules


before_script:
- npm install -g @angular/cli
  npm install --save-dev @angular-devkit/build-angular

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/my-awesome-project
  on:
    branch: master
