language:
- node_js

node_js: "11.2.0"

dist: trusty
sudo: required

branches:
  only:
  - master

cache:
  directories:
  - node_modules

script:
- ng build --base-href https://FlorisKnight.github.io/BookAppV2FrontEnd/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/BookAppV2Angualr
  on:
    branch: master
