language:
- node_js

node_js: "11.2.0"

dist: trusty
sudo: required

branches:
  only:
  - master

cache:
  directories:
  - node_modules

script:
- ng test
- ng build --base-href https://FlorisKnight.github.io/BookAppV2FrontEnd/

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

before_script:
- npm install

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/BookAppV2Angualr
  on:
    branch: master
