language:
- node_js

node_js: "11.2.0"

branches:
only:
- master

before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli

script:
- ionic build --prod --aot

after_success:
- firebase deploy --token $FIREBASE_TOKEN
